### ISSUE TITLE
which python version do you support?

### ISSUE THREAD

**Issue by zdavatz** [miaozn/xsd2xml#2]
With 3.7 I get:

```
~/.software/xsd2xml> ./xsd2xml.py 
Traceback (most recent call last):
  File "./xsd2xml.py", line 4, in <module>
    import xmlschema
ImportError: No module named xmlschema
```

**Comment by maayanorner** [comment]
did you install xmlschema module?
https://pypi.org/project/xmlschema/

I am not sure which versions are compatible with this project though, there are some breaking changes there.

**Comment by zdavatz** [comment]
Thank you!
